### ISSUE TITLE
Error simply executing "npkg folderIn folderOut" (Fedora 20, 64 bits)

### ISSUE THREAD

**Issue by q2dg** [wearefractal/npkg#1]
```
/usr/share/coffee-script/lib/coffee-script/helpers.js:216
      codeLine = codeLine.slice(0, start) + colorize(codeLine.slice(start, end
                          ^
TypeError: Cannot call method 'slice' of undefined
  at Object.exports.prettyErrorMessage (/usr/share/coffee-script/lib/coffee-script/helpers.js:216:27)
  at compileScript (/usr/share/coffee-script/lib/coffee-script/command.js:199:25)
  at /usr/share/coffee-script/lib/coffee-script/command.js:143:18
  at fs.js:266:14
```

**Comment by yocontra** [comment]
Last commit was october 2011 so I'm sure it's a coffee-script compiler change issue. Try installing coffee-script 1.6.0 (or 1.5.0) explicitly in the npkg node_modules and see if that fixes it

**Comment by q2dg** [comment]
Above error was having installed coffee-script via Yum. If I do what you say (npm -g install coffee-script or npm -g install coffee-script@1.5.0, doesn't matter) I have another error:

/usr/lib/node_modules/npkg/lib/main.coffee:37:31: error: octal literal '0755' must be prefixed with '0o'
      fs.mkdirSync dirs[dir], 0755

If I do,  npm -g install coffee-script@1.6.0, the error is:

TypeError: Object #<Object> has no method 'replace'
    at Module._compile (module.js:377:21)
    at Object.exports.run (/usr/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:124:25)
    at compileScript (/usr/lib/node_modules/coffee-script/lib/coffee-script/command.js:166:29)
    at /usr/lib/node_modules/coffee-script/lib/coffee-script/command.js:141:18
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)

Well, I think it's time to move to nexe (https://github.com/crcn/nexe) or something similar.
Thanks!!
